Disable cachix test to spend a bit less $$

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -59,56 +59,56 @@ jobs:
       - name: Test nix
         run: nix-build -v --version
 
-  test-cachix:
-    needs: build
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-        nix_version:
-          - 2.4
-          # - 2.3.15
-          # - 2.3.14
-          # - 2.3.12
-          # - 2.3.10
-          # - 2.3.7
-          # - 2.2.2
-        include:
-          - nix_version: 2.4
-            nix_conf: experimental-features = nix-command flakes
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/download-artifact@v2
-        id: nix-archives
-        with:
-          name: nix-archives-${{ matrix.os }}
-      - uses: ./
-        with:
-          nix_archives_url: file://${{steps.nix-archives.outputs.download-path}}
-          nix_version: ${{ matrix.nix_version }}
-          nix_conf: ${{ matrix.nix_conf }}
-      - uses: cachix/cachix-action@v8
-        with:
-          name: nixbuild
-          signingKey: ${{ secrets.cachix_signing_key }}
-      - name: Verify nix config
-        run: |
-          if ! egrep -q "^substituters = https://cache.nixos.org https://nixbuild.cachix.org$" "$HOME/.config/nix/nix.conf"; then
-            echo "Invalid substituters config"
-            exit 1
-          fi
-      - name: Push to Cachix
-        if: github.event_name == 'push' && github.repository_owner == 'nixbuild'
-        run: |
-          dd if=/dev/urandom of=random count=1
-          cachix push nixbuild "$(nix add-to-store random)"
+  # test-cachix:
+  #   needs: build
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest]
+  #       nix_version:
+  #         - 2.4
+  #         # - 2.3.15
+  #         # - 2.3.14
+  #         # - 2.3.12
+  #         # - 2.3.10
+  #         # - 2.3.7
+  #         # - 2.2.2
+  #       include:
+  #         - nix_version: 2.4
+  #           nix_conf: experimental-features = nix-command flakes
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: actions/download-artifact@v2
+  #       id: nix-archives
+  #       with:
+  #         name: nix-archives-${{ matrix.os }}
+  #     - uses: ./
+  #       with:
+  #         nix_archives_url: file://${{steps.nix-archives.outputs.download-path}}
+  #         nix_version: ${{ matrix.nix_version }}
+  #         nix_conf: ${{ matrix.nix_conf }}
+  #     - uses: cachix/cachix-action@v8
+  #       with:
+  #         name: nixbuild
+  #         signingKey: ${{ secrets.cachix_signing_key }}
+  #     - name: Verify nix config
+  #       run: |
+  #         if ! egrep -q "^substituters = https://cache.nixos.org https://nixbuild.cachix.org$" "$HOME/.config/nix/nix.conf"; then
+  #           echo "Invalid substituters config"
+  #           exit 1
+  #         fi
+  #     - name: Push to Cachix
+  #       if: github.event_name == 'push' && github.repository_owner == 'nixbuild'
+  #       run: |
+  #         dd if=/dev/urandom of=random count=1
+  #         cachix push nixbuild "$(nix add-to-store random)"
 
   release:
     runs-on: ubuntu-latest
     needs:
       - build
       - test-nix
-      - test-cachix
+      # - test-cachix
     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
     steps:
       - uses: actions/checkout@v2
